/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Doctor;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.TestingCentre_TestWorkRequest;
import Business.WorkQueue.MedicineWorkRequest;
import Business.WorkQueue.DoctorSchedule;
import Business.WorkQueue.DoctorScheduleDirectory;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maalp
 */
public class DoctorContainer extends javax.swing.JPanel {
    JPanel container;
    private DoctorOrganization organization;
    private Enterprise enterprise;
    private UserAccount userAccount;
    private DoctorScheduleDirectory scheduleDirectory;
    Network network;

    /**
     * Creates new form DoctorContainer
     */
    public DoctorContainer(JPanel container, UserAccount userAccount, DoctorOrganization organization, Enterprise enterprise, Network network) {
        initComponents();
        this.container=container;
        this.userAccount = userAccount;
        this.organization=organization;
        this.enterprise=enterprise;
        this.network = network;
        scheduleDirectory= userAccount.getScheduleDirectory();
        populateScheduleTable();
        populateLabRequestTable();
        populateMedicineRequestTable();
    }

    
     private void populateScheduleTable()
    {
        DefaultTableModel model = (DefaultTableModel) tblDoctorSchedule.getModel();
        
        model.setRowCount(0);
        
        for (DoctorSchedule schedule : userAccount.getScheduleDirectory().getScheduleList()){
            Object[] row = new Object[4];
            row[0] = schedule.getDate();
            row[1] = schedule.getTime();
            row[2] = schedule.getAvailHours();
            row[3] = schedule;
            model.addRow(row);
    }
    }
     
        private void populateLabRequestTable(){
        DefaultTableModel model = (DefaultTableModel) tblLabRequests.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if(request.getRequestType().contains("Lab"))
            {
            Object[] row = new Object[4];
            row[0] = request.getPatientName();
            row[1] = request;
            row[2] = request.getRequestDate();
            String result = ((TestingCentre_TestWorkRequest) request).getTestResult();
            row[3] = result == null ? "Waiting" : result;
            
            model.addRow(row);
        }
            }
    }
        
        private void populateMedicineRequestTable(){
        DefaultTableModel model = (DefaultTableModel) tblMedicineRequests.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if(request.getRequestType().contains("Medicine"))
            {
            Object[] row = new Object[4];
            row[0] = request.getPatientName();
            row[1] = request;
            row[2] = request.getRequestDate();
            row[3] = request.getStatus();
            
            model.addRow(row);
        }
        }
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        splitPaneDoctor = new javax.swing.JSplitPane();
        DoctorContainerLeftPanel = new javax.swing.JPanel();
        btnCreateSchedule = new javax.swing.JButton();
        btnModifySchedule = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnRequestLabTest = new javax.swing.JButton();
        btnRequestMedicine = new javax.swing.JButton();
        btnViewReports = new javax.swing.JButton();
        DoctorContainerRightJPanel = new javax.swing.JPanel();
        doctorContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDoctorSchedule = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblLabRequests = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblMedicineRequests = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        splitPaneDoctor1 = new javax.swing.JSplitPane();
        DoctorContainerLeftPanel1 = new javax.swing.JPanel();
        btnCreateSchedule1 = new javax.swing.JButton();
        btnModifySchedule1 = new javax.swing.JButton();
        btnCancel1 = new javax.swing.JButton();
        btnRequestLabTest1 = new javax.swing.JButton();
        btnRequestMedicine1 = new javax.swing.JButton();
        btnViewReports1 = new javax.swing.JButton();
        DoctorContainerRightJPanel1 = new javax.swing.JPanel();
        doctorContainer1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDoctorSchedule1 = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        tblLabRequests1 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tblMedicineRequests1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        splitPaneDoctor.setDividerLocation(350);
        splitPaneDoctor.setDividerSize(1);

        DoctorContainerLeftPanel.setBackground(new java.awt.Color(51, 204, 0));

        btnCreateSchedule.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCreateSchedule.setText("Create Schedule");
        btnCreateSchedule.setBorder(new javax.swing.border.MatteBorder(null));
        btnCreateSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateScheduleActionPerformed(evt);
            }
        });

        btnModifySchedule.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnModifySchedule.setText("Modify Schedule");
        btnModifySchedule.setBorder(new javax.swing.border.MatteBorder(null));
        btnModifySchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifyScheduleActionPerformed(evt);
            }
        });

        btnCancel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCancel.setText("Cancel Schedule");
        btnCancel.setBorder(new javax.swing.border.MatteBorder(null));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnRequestLabTest.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnRequestLabTest.setText("Request Lab Test");
        btnRequestLabTest.setBorder(new javax.swing.border.MatteBorder(null));
        btnRequestLabTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestLabTestActionPerformed(evt);
            }
        });

        btnRequestMedicine.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnRequestMedicine.setText("Request Medicine");
        btnRequestMedicine.setBorder(new javax.swing.border.MatteBorder(null));
        btnRequestMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMedicineActionPerformed(evt);
            }
        });

        btnViewReports.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnViewReports.setText("View Report");
        btnViewReports.setBorder(new javax.swing.border.MatteBorder(null));
        btnViewReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReportsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DoctorContainerLeftPanelLayout = new javax.swing.GroupLayout(DoctorContainerLeftPanel);
        DoctorContainerLeftPanel.setLayout(DoctorContainerLeftPanelLayout);
        DoctorContainerLeftPanelLayout.setHorizontalGroup(
            DoctorContainerLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorContainerLeftPanelLayout.createSequentialGroup()
                .addGroup(DoctorContainerLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateSchedule, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DoctorContainerLeftPanelLayout.createSequentialGroup()
                        .addGroup(DoctorContainerLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DoctorContainerLeftPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnModifySchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DoctorContainerLeftPanelLayout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addComponent(btnRequestLabTest, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewReports, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRequestMedicine, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        DoctorContainerLeftPanelLayout.setVerticalGroup(
            DoctorContainerLeftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorContainerLeftPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnCreateSchedule)
                .addGap(78, 78, 78)
                .addComponent(btnModifySchedule)
                .addGap(79, 79, 79)
                .addComponent(btnCancel)
                .addGap(52, 52, 52)
                .addComponent(btnRequestLabTest)
                .addGap(45, 45, 45)
                .addComponent(btnViewReports)
                .addGap(28, 28, 28)
                .addComponent(btnRequestMedicine)
                .addContainerGap(455, Short.MAX_VALUE))
        );

        splitPaneDoctor.setLeftComponent(DoctorContainerLeftPanel);

        DoctorContainerRightJPanel.setLayout(new java.awt.CardLayout());

        doctorContainer.setBackground(new java.awt.Color(51, 204, 0));
        doctorContainer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                doctorContainerComponentShown(evt);
            }
        });

        tblDoctorSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Hours", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblDoctorSchedule);

        tblLabRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Tests", "Request Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblLabRequests);

        tblMedicineRequests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Medicines", "Request Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tblMedicineRequests);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("Doctor Work Space");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel2.setText("Test Request:");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("Schedule:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel5.setText("Medicine Request:");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/sp5.jpg"))); // NOI18N
        jLabel7.setText("jLabel7");

        javax.swing.GroupLayout doctorContainerLayout = new javax.swing.GroupLayout(doctorContainer);
        doctorContainer.setLayout(doctorContainerLayout);
        doctorContainerLayout.setHorizontalGroup(
            doctorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorContainerLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(doctorContainerLayout.createSequentialGroup()
                .addGroup(doctorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(doctorContainerLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(doctorContainerLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(doctorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(doctorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 497, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 382, Short.MAX_VALUE))
        );
        doctorContainerLayout.setVerticalGroup(
            doctorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorContainerLayout.createSequentialGroup()
                .addGroup(doctorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addGroup(doctorContainerLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel1)))
                .addGap(37, 37, 37)
                .addGroup(doctorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(doctorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(50, 50, 50)
                .addGroup(doctorContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(273, Short.MAX_VALUE))
        );

        DoctorContainerRightJPanel.add(doctorContainer, "card2");

        splitPaneDoctor.setRightComponent(DoctorContainerRightJPanel);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneDoctor, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneDoctor)
        );

        splitPaneDoctor1.setDividerLocation(350);
        splitPaneDoctor1.setDividerSize(1);

        DoctorContainerLeftPanel1.setBackground(new java.awt.Color(51, 204, 0));

        btnCreateSchedule1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCreateSchedule1.setText("Create Schedule");
        btnCreateSchedule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateSchedule1ActionPerformed(evt);
            }
        });

        btnModifySchedule1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnModifySchedule1.setText("Modify Schedule");
        btnModifySchedule1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModifySchedule1ActionPerformed(evt);
            }
        });

        btnCancel1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCancel1.setText("Cancel Schedule");
        btnCancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancel1ActionPerformed(evt);
            }
        });

        btnRequestLabTest1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnRequestLabTest1.setText("Request Lab Test");
        btnRequestLabTest1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestLabTest1ActionPerformed(evt);
            }
        });

        btnRequestMedicine1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnRequestMedicine1.setText("Request Medicine");
        btnRequestMedicine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestMedicine1ActionPerformed(evt);
            }
        });

        btnViewReports1.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnViewReports1.setText("View Report");
        btnViewReports1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewReports1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout DoctorContainerLeftPanel1Layout = new javax.swing.GroupLayout(DoctorContainerLeftPanel1);
        DoctorContainerLeftPanel1.setLayout(DoctorContainerLeftPanel1Layout);
        DoctorContainerLeftPanel1Layout.setHorizontalGroup(
            DoctorContainerLeftPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorContainerLeftPanel1Layout.createSequentialGroup()
                .addGroup(DoctorContainerLeftPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCreateSchedule1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(DoctorContainerLeftPanel1Layout.createSequentialGroup()
                        .addGroup(DoctorContainerLeftPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(DoctorContainerLeftPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(btnModifySchedule1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(DoctorContainerLeftPanel1Layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(btnCancel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 70, Short.MAX_VALUE))
                    .addComponent(btnRequestLabTest1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViewReports1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRequestMedicine1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        DoctorContainerLeftPanel1Layout.setVerticalGroup(
            DoctorContainerLeftPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DoctorContainerLeftPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnCreateSchedule1)
                .addGap(78, 78, 78)
                .addComponent(btnModifySchedule1)
                .addGap(124, 124, 124)
                .addComponent(btnCancel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                .addComponent(btnRequestLabTest1)
                .addGap(118, 118, 118)
                .addComponent(btnViewReports1)
                .addGap(111, 111, 111)
                .addComponent(btnRequestMedicine1)
                .addGap(139, 139, 139))
        );

        splitPaneDoctor1.setLeftComponent(DoctorContainerLeftPanel1);

        DoctorContainerRightJPanel1.setLayout(new java.awt.CardLayout());

        doctorContainer1.setBackground(new java.awt.Color(51, 204, 0));
        doctorContainer1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                doctorContainer1ComponentShown(evt);
            }
        });

        tblDoctorSchedule1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Hours", "Location"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tblDoctorSchedule1);

        tblLabRequests1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Tests", "Request Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(tblLabRequests1);

        tblMedicineRequests1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "Medicines", "Request Date", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tblMedicineRequests1);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        jLabel4.setText("Doctor Work Space");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setText("Test Request:");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel8.setText("Schedule:");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel9.setText("Medicine Request:");

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/sp5.jpg"))); // NOI18N
        jLabel10.setText("jLabel7");

        javax.swing.GroupLayout doctorContainer1Layout = new javax.swing.GroupLayout(doctorContainer1);
        doctorContainer1.setLayout(doctorContainer1Layout);
        doctorContainer1Layout.setHorizontalGroup(
            doctorContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorContainer1Layout.createSequentialGroup()
                .addContainerGap(304, Short.MAX_VALUE)
                .addGroup(doctorContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(doctorContainer1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 391, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(98, 98, 98))
                    .addGroup(doctorContainer1Layout.createSequentialGroup()
                        .addGroup(doctorContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 502, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(doctorContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                                .addComponent(jScrollPane5)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        doctorContainer1Layout.setVerticalGroup(
            doctorContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(doctorContainer1Layout.createSequentialGroup()
                .addGroup(doctorContainer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addGroup(doctorContainer1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addComponent(jLabel8)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jLabel9)
                .addGap(37, 37, 37)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        DoctorContainerRightJPanel1.add(doctorContainer1, "card2");

        splitPaneDoctor1.setRightComponent(DoctorContainerRightJPanel1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneDoctor1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPaneDoctor1)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1486, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1486, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1016, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateScheduleActionPerformed
        DoctorCreateSchedule doctorCreateSchedule =new DoctorCreateSchedule(DoctorContainerRightJPanel, userAccount, scheduleDirectory);
        DoctorContainerRightJPanel.add("DoctorCreateSchedule", doctorCreateSchedule);
        CardLayout layout=(CardLayout) DoctorContainerRightJPanel.getLayout();
        layout.next(DoctorContainerRightJPanel);
        btnCreateSchedule.setEnabled(false);
        btnModifySchedule.setEnabled(false);
        btnRequestMedicine.setEnabled(false);
        btnRequestLabTest.setEnabled(false);
        btnCancel.setEnabled(false);
        btnViewReports.setEnabled(false);

    }//GEN-LAST:event_btnCreateScheduleActionPerformed

    private void btnModifyScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifyScheduleActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDoctorSchedule.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            DoctorSchedule schedule = (DoctorSchedule) tblDoctorSchedule.getValueAt(selectedRow, 3);
            DoctorModifySchedule doctorModifySchedule = new DoctorModifySchedule(DoctorContainerRightJPanel, userAccount, schedule);
            DoctorContainerRightJPanel.add("modifyDoctorSchedule", doctorModifySchedule);
            CardLayout layout = (CardLayout) DoctorContainerRightJPanel.getLayout();
            layout.next(DoctorContainerRightJPanel);
            btnCreateSchedule.setEnabled(false);
            btnRequestLabTest.setEnabled(false);
            btnRequestMedicine.setEnabled(false);
            btnCancel.setEnabled(false);
            btnModifySchedule.setEnabled(false);
            btnViewReports.setEnabled(false);
        }
    }//GEN-LAST:event_btnModifyScheduleActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblDoctorSchedule.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            DoctorSchedule schedule = (DoctorSchedule) tblDoctorSchedule.getValueAt(selectedRow, 3);
            userAccount.getScheduleDirectory().cancelSchedule(schedule);
            populateScheduleTable();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnRequestLabTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestLabTestActionPerformed
        // TODO add your handling code here:
        Doctor_TestCentre docterLabTestRequest =new Doctor_TestCentre(DoctorContainerRightJPanel, userAccount, enterprise);
        DoctorContainerRightJPanel.add("Lab Test Request", docterLabTestRequest);
        CardLayout layout=(CardLayout) DoctorContainerRightJPanel.getLayout();
        layout.next(DoctorContainerRightJPanel);
        btnCreateSchedule.setEnabled(false);
        btnModifySchedule.setEnabled(false);
        btnRequestMedicine.setEnabled(false);
        btnRequestLabTest.setEnabled(false);
        btnCancel.setEnabled(false);
        btnViewReports.setEnabled(false);
    }//GEN-LAST:event_btnRequestLabTestActionPerformed

    private void btnRequestMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMedicineActionPerformed
        // TODO add your handling code here:
        DoctorMedicalRequest doctorMedicineRequest =new DoctorMedicalRequest(DoctorContainerRightJPanel, userAccount, enterprise);
        DoctorContainerRightJPanel.add("Lab Test Request", doctorMedicineRequest);
        CardLayout layout=(CardLayout) DoctorContainerRightJPanel.getLayout();
        layout.next(DoctorContainerRightJPanel);
        btnCreateSchedule.setEnabled(false);
        btnModifySchedule.setEnabled(false);
        btnRequestMedicine.setEnabled(false);
        btnRequestLabTest.setEnabled(false);
        btnCancel.setEnabled(false);
        btnViewReports.setEnabled(false);

    }//GEN-LAST:event_btnRequestMedicineActionPerformed

    private void btnViewReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReportsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblLabRequests.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            TestingCentre_TestWorkRequest request = (TestingCentre_TestWorkRequest) tblLabRequests.getValueAt(selectedRow, 1);
            DoctorViewReports doctorViewReports =new DoctorViewReports(DoctorContainerRightJPanel, userAccount, request);
            DoctorContainerRightJPanel.add("doctorViewReports", doctorViewReports);
            CardLayout layout=(CardLayout) DoctorContainerRightJPanel.getLayout();
            layout.next(DoctorContainerRightJPanel);
            btnCreateSchedule.setEnabled(false);
            btnModifySchedule.setEnabled(false);
            btnRequestMedicine.setEnabled(false);
            btnRequestLabTest.setEnabled(false);
            btnCancel.setEnabled(false);
            btnViewReports.setEnabled(false);

        }
    }//GEN-LAST:event_btnViewReportsActionPerformed

    private void doctorContainerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_doctorContainerComponentShown
        // TODO add your handling code here:
        btnCreateSchedule.setEnabled(true);
        btnModifySchedule.setEnabled(true);
        btnRequestMedicine.setEnabled(true);
        btnRequestLabTest.setEnabled(true);
        btnCancel.setEnabled(true);
        btnViewReports.setEnabled(true);
        populateScheduleTable();
        populateLabRequestTable();
        populateMedicineRequestTable();
    }//GEN-LAST:event_doctorContainerComponentShown

    private void doctorContainer1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_doctorContainer1ComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_doctorContainer1ComponentShown

    private void btnViewReports1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewReports1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnViewReports1ActionPerformed

    private void btnRequestMedicine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestMedicine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequestMedicine1ActionPerformed

    private void btnRequestLabTest1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestLabTest1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRequestLabTest1ActionPerformed

    private void btnCancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancel1ActionPerformed

    private void btnModifySchedule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModifySchedule1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModifySchedule1ActionPerformed

    private void btnCreateSchedule1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateSchedule1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCreateSchedule1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DoctorContainerLeftPanel;
    private javax.swing.JPanel DoctorContainerLeftPanel1;
    private javax.swing.JPanel DoctorContainerRightJPanel;
    private javax.swing.JPanel DoctorContainerRightJPanel1;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnCancel1;
    private javax.swing.JButton btnCreateSchedule;
    private javax.swing.JButton btnCreateSchedule1;
    private javax.swing.JButton btnModifySchedule;
    private javax.swing.JButton btnModifySchedule1;
    private javax.swing.JButton btnRequestLabTest;
    private javax.swing.JButton btnRequestLabTest1;
    private javax.swing.JButton btnRequestMedicine;
    private javax.swing.JButton btnRequestMedicine1;
    private javax.swing.JButton btnViewReports;
    private javax.swing.JButton btnViewReports1;
    private javax.swing.JPanel doctorContainer;
    private javax.swing.JPanel doctorContainer1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSplitPane splitPaneDoctor;
    private javax.swing.JSplitPane splitPaneDoctor1;
    private javax.swing.JTable tblDoctorSchedule;
    private javax.swing.JTable tblDoctorSchedule1;
    private javax.swing.JTable tblLabRequests;
    private javax.swing.JTable tblLabRequests1;
    private javax.swing.JTable tblMedicineRequests;
    private javax.swing.JTable tblMedicineRequests1;
    // End of variables declaration//GEN-END:variables
}
