/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Doctor;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.Schedule;
import Business.WorkQueue.ScheduleDirectory;
import java.awt.CardLayout;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author maalp
 */
public class DoctorCreateScheduleOld extends javax.swing.JPanel {
    JPanel doctorContainerRightJPanel;
    UserAccount userAccount;
    ScheduleDirectory scheduleDirectory;

    /**
     * Creates new form DoctorCreateSchedule
     */
    public DoctorCreateScheduleOld(JPanel container, UserAccount userAccount, ScheduleDirectory scheduleDirectory) {
        initComponents();
        this.doctorContainerRightJPanel=container;
        this.userAccount = userAccount;
        this.scheduleDirectory=scheduleDirectory;
        DateFormat df = new SimpleDateFormat("dd/MM/yy");
        Date date = new Date();
        
        datefield.setDate(date);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        dateLabel = new javax.swing.JLabel();
        timeLabel = new javax.swing.JLabel();
        hoursLabel = new javax.swing.JLabel();
        txtHours = new javax.swing.JTextField();
        locationLabel = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        banner = new javax.swing.JLabel();
        btnCreateSchedule = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        txtTime = new javax.swing.JComboBox();
        datefield = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));

        dateLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        dateLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateLabel.setText("Date:");

        timeLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        timeLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        timeLabel.setText("Time:");

        hoursLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        hoursLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        hoursLabel.setText("Hours:");

        txtHours.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        locationLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        locationLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        locationLabel.setText("Location:");

        txtLocation.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N

        banner.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        banner.setText("Doctor : Create Schedule");

        btnCreateSchedule.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnCreateSchedule.setText("Create Schedule");
        btnCreateSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateScheduleActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnBack.setText("<< Back");
        btnBack.setBorder(new javax.swing.border.MatteBorder(null));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        txtTime.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "9:00AM", "10:00AM", "11:00AM", "12:00PM", "1:00PM", "2:00PM", "3:00PM", "4:00PM", "5:00PM" }));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/sp5.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(dateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(locationLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(hoursLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnCreateSchedule, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(215, 215, 215)))
                        .addGap(44, 44, 44))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(banner)
                        .addGap(197, 197, 197)))
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(banner)))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(dateLabel)
                        .addComponent(datefield, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(timeLabel))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(hoursLabel)
                        .addComponent(txtHours, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(locationLabel)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnCreateSchedule)
                .addGap(54, 54, 54)
                .addComponent(btnBack)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateScheduleActionPerformed
        // TODO add your handling code here:

        DateFormat df = new SimpleDateFormat("dd/MM/yy");
        Date date = new Date();

        Date localDate;
        if(!(datefield.getDate().toString().isEmpty()))
        {localDate=datefield.getDate();

            if(localDate.compareTo(date) ==-1)
            JOptionPane.showMessageDialog(null, "PLEASE CHOOSE FUTURE DATES!","INFORMATION",JOptionPane.INFORMATION_MESSAGE);
            else if(!txtHours.getText().matches("[1-9]"))
            JOptionPane.showMessageDialog(null, "PLEASE ENTTER HOURS BETWEEN 1 TO 9","WARNING",JOptionPane.WARNING_MESSAGE);
            else if(!txtLocation.getText().matches("[[A-Za-z]*[0-9]*[A-Za-z]]*"))
            JOptionPane.showMessageDialog(null, "PLEASE ENTTER AALPHABETS AND DIGITS ONLY","WARNING",JOptionPane.WARNING_MESSAGE);
            else if(txtHours.getText().isEmpty() || txtLocation.getText().isEmpty() )
            JOptionPane.showMessageDialog(null, "PLEASE ENTTER Values in  all fields","WARNING",JOptionPane.WARNING_MESSAGE);
            else{
                Schedule schedule = userAccount.getScheduleDirectory().add();
                String timeabb=(String) txtTime.getSelectedItem();
                timeabb=timeabb.substring(0, timeabb.length() - 5);

                schedule.setDate(datefield.getDate());
                schedule.setAvailHours((int) Float.parseFloat(txtHours.getText()));
                schedule.setLocation(txtLocation.getText());
                schedule.setTime(timeabb);

                txtHours.setText(null);
                txtLocation.setText(null);
                txtTime.setSelectedIndex(0);
                JOptionPane.showMessageDialog(null, "Schedule Created","Success",JOptionPane.INFORMATION_MESSAGE);
            }
        }
        else
        JOptionPane.showMessageDialog(null, "PLEASE CHOOSE a DATE","WARNING",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnCreateScheduleActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        doctorContainerRightJPanel.remove(this);
        CardLayout layout = (CardLayout) doctorContainerRightJPanel.getLayout();
        layout.previous(doctorContainerRightJPanel);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel banner;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreateSchedule;
    private javax.swing.JLabel dateLabel;
    private com.toedter.calendar.JDateChooser datefield;
    private javax.swing.JLabel hoursLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel locationLabel;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JTextField txtHours;
    private javax.swing.JTextField txtLocation;
    private javax.swing.JComboBox txtTime;
    // End of variables declaration//GEN-END:variables
}
