/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Pharmacist;
import Business.Inventory.Medicine;
import Business.Inventory.MedicineDirectory;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.MedicineWorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maalp
 */
public class MedicineSupplyOld extends javax.swing.JPanel {
    JPanel rightJPanel;
    UserAccount userAccount;
    MedicineDirectory medicineDirectory;
    MedicineWorkRequest request;

    /**
     * Creates new form MedicineSupply
     */
    public MedicineSupplyOld(JPanel container, UserAccount userAccount, MedicineDirectory medicineDirectory, MedicineWorkRequest request) {
        initComponents();
        this.rightJPanel=container;
        this.userAccount=userAccount;
        this.medicineDirectory= medicineDirectory;
        populateMedicineTable();
        this.request = request;
    }

    
      public void populateMedicineTable()
    {
         DefaultTableModel model = (DefaultTableModel) tblMedicines.getModel();
         
         model.setRowCount(0);
         for(Medicine medicine: medicineDirectory.getMedicineList())
         {
           Object[] row= new Object[2];
           row[0]=medicine;
           row[1]= medicine.getQuantity();
           model.addRow(row);
         }
     
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSupplyMedicine = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMedicinesSupply = new javax.swing.JTable();
        btnAdd = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicines = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        lblBanner = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 204, 0));

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));

        btnSupplyMedicine.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnSupplyMedicine.setText("Supply Medicine");
        btnSupplyMedicine.setBorder(new javax.swing.border.MatteBorder(null));
        btnSupplyMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSupplyMedicineActionPerformed(evt);
            }
        });

        tblMedicinesSupply.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tblMedicinesSupply.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine", "Quantity"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMedicinesSupply.setRowHeight(30);
        jScrollPane2.setViewportView(tblMedicinesSupply);

        btnAdd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        btnAdd.setText("ADD>>>");
        btnAdd.setBorder(new javax.swing.border.MatteBorder(null));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        tblMedicines.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tblMedicines.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Medicine", "Available Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMedicines.setRowHeight(30);
        jScrollPane1.setViewportView(tblMedicines);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(btnSupplyMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(225, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(btnAdd)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(74, 74, 74)
                .addComponent(btnSupplyMedicine)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos/sp5.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");

        lblBanner.setFont(new java.awt.Font("Times New Roman", 0, 48)); // NOI18N
        lblBanner.setText("Pharmacist Medicine Supply");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(lblBanner)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lblBanner))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 626, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSupplyMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSupplyMedicineActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model1 = (DefaultTableModel) tblMedicines.getModel();
        DefaultTableModel model2 = (DefaultTableModel) tblMedicinesSupply.getModel();
        int rowCount1 = model1.getRowCount();
        int rowCount2 = model2.getRowCount();
        if((Integer)model2.getRowCount() == null)
        {
            model2.setRowCount(0);
            System.out.println("abc= "+model2.getRowCount());
        }
        for(int i = 0; i < rowCount2; i++)
        {
            System.out.println("qwerty"+model2.getRowCount());

            System.out.println("value= "+model2.getValueAt(i, 1));
            int quantity = (int) model2.getValueAt(i,1);
            for(int j = 0; j < rowCount1; j++ )
            {
                System.out.println("model2=  "+ model2.getValueAt(i, 0) + "     model1 =  "+model1.getValueAt(j, 0));
                if(model2.getValueAt(i, 0).toString().equalsIgnoreCase(model1.getValueAt(j, 0).toString()))

                {
                    Medicine medicine= (Medicine) tblMedicines.getValueAt(j,0);
                    System.out.println("medicine quantity= "+ medicine.getQuantity());
                    System.out.println(" quantity= "+ quantity);
                    medicine.setQuantity(medicine.getQuantity() - quantity);

                    break;
                }

            }

        }
        request.setComments("completed");
        request.setStatus("Completed");
        JOptionPane.showMessageDialog(null, "Medicine Request Successful");
        rightJPanel.remove(this);
        CardLayout layout = (CardLayout) rightJPanel.getLayout();
        layout.previous(rightJPanel);
    }//GEN-LAST:event_btnSupplyMedicineActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        int selectedRow= tblMedicines.getSelectedRow();
        System.out.println("selected row"+ tblMedicines.getSelectedRow());
        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else
        {
            System.out.println("table medicine get name"+ tblMedicines.getValueAt(selectedRow,0));
            System.out.println("table medicine get value"+ tblMedicines.getValueAt(selectedRow,1));
            Medicine medicine = new Medicine(tblMedicines.getValueAt(selectedRow,0).toString(),Integer.parseInt(tblMedicines.getValueAt(selectedRow,1).toString()));
            DefaultTableModel model = (DefaultTableModel) tblMedicinesSupply.getModel();
            Object[] row= new Object[1];
            row[0]=medicine;
            model.addRow(row);
            populateMedicineTable();
        }
    }//GEN-LAST:event_btnAddActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnSupplyMedicine;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JTable tblMedicines;
    private javax.swing.JTable tblMedicinesSupply;
    // End of variables declaration//GEN-END:variables
}
