/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorAssistant;
import Business.Enterprise.RedCrossEnterprise;
import Business.Enterprise.Enterprise;
import Business.Inventory.RedCross_Blood;
import Business.Network.Network;
import Business.Organization.RedCrossOrganization;
import Business.Organization.DoctorAssistantOrganization;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RedCross_BloodRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maalp
 */
public class BloodStorage extends javax.swing.JPanel {
    DoctorAssistantOrganization nurseOrganization;
    JPanel rightPanel;
    Network network;
    UserAccount userAccount;

    /**
     * Creates new form BloodStorage
     */
    public BloodStorage(JPanel rightPanel, Organization organization, Network network, UserAccount userAccount) {
        initComponents();
        this.rightPanel = rightPanel;
        this.nurseOrganization = (DoctorAssistantOrganization)organization;
        this.network = network;
        this.userAccount = userAccount;
        populateTable();
    }
    
    
      private void populateTable()
    {
        DefaultTableModel model = (DefaultTableModel)tblBlood.getModel();
        
        model.setRowCount(0);
        
        for(RedCross_Blood blood : nurseOrganization.getBloodDirectory().getBloodDirectory()){
            Object[] row = new Object[4];
            row[0] = blood;
            row[1] = blood.getQuantity();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBlood = new javax.swing.JTable();
        btnRequestBlood = new javax.swing.JButton();
        btnBank = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 204, 0));

        jPanel1.setBackground(new java.awt.Color(51, 204, 0));

        tblBlood.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tblBlood.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Blood type", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBlood.setRowHeight(30);
        jScrollPane1.setViewportView(tblBlood);

        btnRequestBlood.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnRequestBlood.setText("Request Blood");
        btnRequestBlood.setBorder(new javax.swing.border.MatteBorder(null));
        btnRequestBlood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRequestBloodActionPerformed(evt);
            }
        });

        btnBank.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBank.setText("<< Back");
        btnBank.setBorder(new javax.swing.border.MatteBorder(null));
        btnBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBankActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setText("View Blood Storage");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnBank, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63)
                        .addComponent(btnRequestBlood, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnBank)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(btnRequestBlood)))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRequestBloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRequestBloodActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBlood.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please Select a Row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            RedCross_Blood blood  =  (RedCross_Blood) tblBlood.getValueAt(selectedRow,0);
            RedCross_BloodRequest request = new RedCross_BloodRequest();
            request.setMessage(blood.getType());
            request.setPatientName(nurseOrganization.getName());
            request.setStatus("Sent");
            request.setRequestType("Blood Request");

            Enterprise ent = null;
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
            {
                if(enterprise instanceof RedCrossEnterprise)
                {
                    //JOptionPane.showMessageDialog(null, "check");
                    ent = enterprise;
                    Organization org = null;
                    for (Organization organization : ent.getOrganizationDirectory().getOrganizationList()){
                        if (organization instanceof RedCrossOrganization){
                            org = organization;
                            if (org!=null)
                            {
                                JOptionPane.showMessageDialog(null, "check");
                                org.getWorkQueue().getWorkRequestList().add(request);
                                break;
                            }

                        }

                        //userAccount.getWorkQueue().getWorkRequestList().add(request);
                        //nurseOrganization.getWorkQueue().getWorkRequestList().add(request);
                    }

                }
            }

            nurseOrganization.getWorkQueue().getWorkRequestList().add(request);
            JOptionPane.showMessageDialog(null, "Blood Request Successful");
            rightPanel.remove(this);
            CardLayout layout = (CardLayout) rightPanel.getLayout();
            layout.previous(rightPanel);
        }
    }//GEN-LAST:event_btnRequestBloodActionPerformed

    private void btnBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBankActionPerformed
        // TODO add your handling code here:
        rightPanel.remove(this);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnBankActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBank;
    private javax.swing.JButton btnRequestBlood;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBlood;
    // End of variables declaration//GEN-END:variables
}
