/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.DoctorAssistant;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.DoctorAssistantOrganization;
import Business.Recipient.Recipient;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.RedCross_BloodRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author maalp
 */
public class DoctorAssistantWorkSpace extends javax.swing.JPanel {
    JPanel container;
    DoctorAssistantOrganization nurseOrganization;
    UserAccount userAccount;
    Enterprise enterprise;
    Network network;

    /**
     * Creates new form NurseWorkSpace
     */
    public DoctorAssistantWorkSpace(JPanel container, UserAccount account, DoctorAssistantOrganization nurseOrganization, Enterprise enterprise, Network network) {
        initComponents();
        this.container = container;
        this.nurseOrganization = nurseOrganization;
        this.userAccount = account;
        this.enterprise = enterprise;
        this.network = network;
        refreshTable();
        populateBloodRequestTable();
       
    }

    
    
    
    public void refreshTable()
    {
        DefaultTableModel dtm = (DefaultTableModel) tblPatient.getModel();
        dtm.setRowCount(0);
        for(Recipient patient : nurseOrganization.getPatientDirectory().getPatientList()){
           Object[] row = new Object[3];
           row[0] = patient.getPatientID();
           row[1] = patient;
           row[2] = patient.getDateAdmitted();
            
           dtm.addRow(row);
    }
    }
    
     private void populateBloodRequestTable()
    {
        DefaultTableModel model = (DefaultTableModel)tblBloodRequest.getModel();
        
        model.setRowCount(0);
        
        for(WorkRequest request : nurseOrganization.getWorkQueue().getWorkRequestList()){
            Object[] row = new Object[5];
            row[0] = request.getRequestDate();
            row[1] = request.getPatientName();
            row[2] = request;
            row[3] = request.getReceiver() == null ? null : request.getReceiver().getEmployee().getName();
            row[4] = request.getStatus();
            
            model.addRow(row);
        }
    }
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        leftPanel = new javax.swing.JPanel();
        leftPanel1 = new javax.swing.JPanel();
        btnRegisterPatient = new javax.swing.JButton();
        btnRecordVitalSigns = new javax.swing.JButton();
        btnDischargePatient = new javax.swing.JButton();
        btnPatientHistory = new javax.swing.JButton();
        btnHome = new javax.swing.JButton();
        btnBloodBank = new javax.swing.JButton();
        rightPanel = new javax.swing.JPanel();
        nurseContainer = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPatient = new javax.swing.JTable();
        btnAccept = new javax.swing.JButton();
        lblBanner = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBloodRequest = new javax.swing.JTable();

        jPanel1.setLayout(new java.awt.BorderLayout());

        leftPanel1.setBackground(new java.awt.Color(51, 204, 0));

        btnRegisterPatient.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnRegisterPatient.setText("Register Patient");
        btnRegisterPatient.setBorder(new javax.swing.border.MatteBorder(null));
        btnRegisterPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterPatientActionPerformed(evt);
            }
        });

        btnRecordVitalSigns.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnRecordVitalSigns.setText("Record Vital Signs");
        btnRecordVitalSigns.setBorder(new javax.swing.border.MatteBorder(null));
        btnRecordVitalSigns.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecordVitalSignsActionPerformed(evt);
            }
        });

        btnDischargePatient.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnDischargePatient.setText("Discharge Patient");
        btnDischargePatient.setBorder(new javax.swing.border.MatteBorder(null));
        btnDischargePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDischargePatientActionPerformed(evt);
            }
        });

        btnPatientHistory.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnPatientHistory.setText("View Patient History");
        btnPatientHistory.setBorder(new javax.swing.border.MatteBorder(null));
        btnPatientHistory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPatientHistoryActionPerformed(evt);
            }
        });

        btnHome.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnHome.setText("Home");
        btnHome.setBorder(new javax.swing.border.MatteBorder(null));
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnBloodBank.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnBloodBank.setText("View Blood Reserve");
        btnBloodBank.setBorder(new javax.swing.border.MatteBorder(null));
        btnBloodBank.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBloodBankActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftPanel1Layout = new javax.swing.GroupLayout(leftPanel1);
        leftPanel1.setLayout(leftPanel1Layout);
        leftPanel1Layout.setHorizontalGroup(
            leftPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(leftPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftPanel1Layout.createSequentialGroup()
                        .addGroup(leftPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPatientHistory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRecordVitalSigns, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnRegisterPatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDischargePatient, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addComponent(btnBloodBank, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftPanel1Layout.setVerticalGroup(
            leftPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(btnHome)
                .addGap(77, 77, 77)
                .addComponent(btnRegisterPatient)
                .addGap(78, 78, 78)
                .addComponent(btnRecordVitalSigns)
                .addGap(78, 78, 78)
                .addComponent(btnPatientHistory)
                .addGap(77, 77, 77)
                .addComponent(btnDischargePatient)
                .addGap(76, 76, 76)
                .addComponent(btnBloodBank)
                .addContainerGap(264, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftPanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(leftPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addComponent(leftPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(leftPanel);

        rightPanel.setLayout(new java.awt.CardLayout());

        nurseContainer.setBackground(new java.awt.Color(51, 204, 0));
        nurseContainer.setPreferredSize(new java.awt.Dimension(1134, 1014));
        nurseContainer.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                nurseContainerComponentShown(evt);
            }
        });

        tblPatient.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tblPatient.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Date Admitted"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPatient.setRowHeight(30);
        jScrollPane1.setViewportView(tblPatient);

        btnAccept.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        btnAccept.setText("Accept");
        btnAccept.setBorder(new javax.swing.border.MatteBorder(null));
        btnAccept.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcceptActionPerformed(evt);
            }
        });

        lblBanner.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        lblBanner.setText("Doctor Assistant Work Space");

        tblBloodRequest.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        tblBloodRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Request Date", "Sender", "Blood Type", "Receiver", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblBloodRequest.setRowHeight(30);
        jScrollPane4.setViewportView(tblBloodRequest);

        javax.swing.GroupLayout nurseContainerLayout = new javax.swing.GroupLayout(nurseContainer);
        nurseContainer.setLayout(nurseContainerLayout);
        nurseContainerLayout.setHorizontalGroup(
            nurseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(nurseContainerLayout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addGroup(nurseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBanner)
                    .addGroup(nurseContainerLayout.createSequentialGroup()
                        .addGroup(nurseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 515, Short.MAX_VALUE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(45, 45, 45)
                        .addComponent(btnAccept, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 409, Short.MAX_VALUE))
        );
        nurseContainerLayout.setVerticalGroup(
            nurseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, nurseContainerLayout.createSequentialGroup()
                .addComponent(lblBanner)
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(nurseContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(nurseContainerLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(nurseContainerLayout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(btnAccept)))
                .addContainerGap(298, Short.MAX_VALUE))
        );

        rightPanel.add(nurseContainer, "card2");

        jSplitPane1.setRightComponent(rightPanel);

        jPanel1.add(jSplitPane1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(304, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 943, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterPatientActionPerformed
        // TODO add your handling code here:
        PatientRegister panel = new PatientRegister(rightPanel, nurseOrganization);
        rightPanel.add("Register New Patient",panel);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
        btnRegisterPatient.setEnabled(false);
        btnBloodBank.setEnabled(false);
        btnDischargePatient.setEnabled(false);
        btnRecordVitalSigns.setEnabled(false);
        btnPatientHistory.setEnabled(false);
    }//GEN-LAST:event_btnRegisterPatientActionPerformed

    private void btnRecordVitalSignsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecordVitalSignsActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatient.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please Select a Row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            btnRegisterPatient.setEnabled(false);
            btnBloodBank.setEnabled(false);
            btnDischargePatient.setEnabled(false);
            btnRecordVitalSigns.setEnabled(false);
            btnPatientHistory.setEnabled(false);
            Recipient patient  =  (Recipient) tblPatient.getValueAt(selectedRow,1);
            VitalSignRecord recordVitalSigns = new VitalSignRecord(rightPanel, patient);
            rightPanel.add("RecordvitalSigns", recordVitalSigns);
            CardLayout layout = (CardLayout) rightPanel.getLayout();
            layout.next(rightPanel);
        }
    }//GEN-LAST:event_btnRecordVitalSignsActionPerformed

    private void btnDischargePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDischargePatientActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatient.getSelectedRow();
        if(selectedRow >= 0){
            int dialogResult = JOptionPane.showConfirmDialog(null,"Is the patient's disease treated successfully and want to discharge?","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                Recipient patient= (Recipient) tblPatient.getValueAt(selectedRow,1);
                DefaultTableModel dtm=(DefaultTableModel) tblPatient.getModel();
                dtm.removeRow(selectedRow);
                refreshTable();
            }
        }
        else
        JOptionPane.showMessageDialog(null, "PLEASE SELECT A ROW","WARNING",JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_btnDischargePatientActionPerformed

    private void btnPatientHistoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPatientHistoryActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblPatient.getSelectedRow();
        if(selectedRow < 0){
            JOptionPane.showMessageDialog(null,"Please Select a Row from table first","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            btnRegisterPatient.setEnabled(false);
            btnBloodBank.setEnabled(false);
            btnDischargePatient.setEnabled(false);
            btnRecordVitalSigns.setEnabled(false);
            btnPatientHistory.setEnabled(false);
            Recipient patient  = (Recipient) tblPatient.getValueAt(selectedRow,1);
            PatientHistory patientHistory = new PatientHistory(rightPanel, patient);
            rightPanel.add("Patient History", patientHistory);
            CardLayout layout = (CardLayout) rightPanel.getLayout();
            layout.next(rightPanel);
        }
    }//GEN-LAST:event_btnPatientHistoryActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        rightPanel.removeAll();
        rightPanel.add(nurseContainer);
        refreshTable();
        populateBloodRequestTable();
        btnRegisterPatient.setEnabled(true);
        btnBloodBank.setEnabled(true);
        btnDischargePatient.setEnabled(true);
        btnRecordVitalSigns.setEnabled(true);
        btnPatientHistory.setEnabled(true);
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnBloodBankActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBloodBankActionPerformed
        // TODO add your handling code here:
        btnRegisterPatient.setEnabled(false);
        btnBloodBank.setEnabled(false);
        btnDischargePatient.setEnabled(false);
        btnRecordVitalSigns.setEnabled(false);
        btnPatientHistory.setEnabled(false);
        BloodStorage viewBloodBank = new BloodStorage(rightPanel, nurseOrganization, network, userAccount);
        rightPanel.add("Blood Bank", viewBloodBank);
        CardLayout layout = (CardLayout) rightPanel.getLayout();
        layout.next(rightPanel);
    }//GEN-LAST:event_btnBloodBankActionPerformed

    private void btnAcceptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcceptActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblBloodRequest.getSelectedRow();

        if (selectedRow < 0){
            JOptionPane.showMessageDialog(null, "Please select a row!!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{
            RedCross_BloodRequest request = (RedCross_BloodRequest)tblBloodRequest.getValueAt(selectedRow, 2);
            if(request.getStatus().equalsIgnoreCase("Processed"))
            {
                request.setStatus("Completed");
                populateBloodRequestTable();
            }
            else
            {
                JOptionPane.showMessageDialog(null, "Sorry this request is not processed yet!!!", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnAcceptActionPerformed

    private void nurseContainerComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_nurseContainerComponentShown
        refreshTable();
        populateBloodRequestTable();
        btnRegisterPatient.setEnabled(true);
        btnBloodBank.setEnabled(true);
        btnDischargePatient.setEnabled(true);
        btnRecordVitalSigns.setEnabled(true);
        btnPatientHistory.setEnabled(true);
    }//GEN-LAST:event_nurseContainerComponentShown


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAccept;
    private javax.swing.JButton btnBloodBank;
    private javax.swing.JButton btnDischargePatient;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnPatientHistory;
    private javax.swing.JButton btnRecordVitalSigns;
    private javax.swing.JButton btnRegisterPatient;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblBanner;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPanel leftPanel1;
    private javax.swing.JPanel nurseContainer;
    private javax.swing.JPanel rightPanel;
    private javax.swing.JTable tblBloodRequest;
    private javax.swing.JTable tblPatient;
    // End of variables declaration//GEN-END:variables
}
